<?php
// Oauth
const EMAIL_RENDER_WELCOME = 0;
const EMAIL_RENDER_RESET_PASSWORD = 1;
const EMAIL_RENDER_SEND_OTP = 2;
const EMAIL_RENDER_VERIFY_EMAIL = 3;

// Profile
const EMAIL_RENDER_RESET_EMAIL_ADDRESS = 4;